### PR TITLE
minimize rerendering of disqus component

### PR DESCRIPTION
**Pull request by dkent600**
Resolves: https://daostack.tpondemand.com/RestUI/Board.aspx#page=board/5209716961861964288&appConfig=eyJhY2lkIjoiQjgzMTMzNDczNzlCMUI5QUE0RUE1NUVEOUQyQzdFNkIifQ==&boardPopup=bug/1785/silent

BTW, I think we could probably reduce a lot of rendering elsewhere in the app by using the same solution as used in this PR.

### CODE REVIEW

**Comment by tibetsprague** [comment]
also as far as I know this always used to work, the re-rendering only started recently

**Comment by dkent600** [comment]
@tibetsprague 

> I don't understand why this changes anything, can you explain?

We were passing a new instance of `disqusConfig ` into `DiscussionEmbed` on each render of ProposalDetailsPage.  This made react think that DiscussionEmbed needed to be re-rendered, when in fact it didn't.

**Comment by tibetsprague** [comment]
huh, odd. that should not be an issue, Disqus even does it the way we were doing it in their primary example code: https://github.com/disqus/disqus-react

**Comment by dkent600** [comment]
@tibetsprague 

> that should not be an issue,

It is a generic issue that I've read about in react articles on minimizing renders.

**Comment by jellegerbrandy** [comment]
If I understand this correctly: before this PR, any time the proposaldetailspage is rendered, we create a new disqusconfig, and so also re-render the disqus subcomponent. After this PR, the disqus subcomponent is not re-rendered every time proposaldetailspage changes.

The fact that this was not a problem before, but became a problem now, may be dus to the proposalsdetailspage being rendered more often (?)

**Comment by dkent600** [comment]
> may be due to the proposalsdetailspage being rendered more often (?)

That occurred to me too.  Pretty much the only explanation I think.

**Pull request merged**
