### PR TITLE
No DAOstack Logo

### PR DESCRIPTION
**Pull request by dOrgJelli**
Closes https://github.com/daostack/alchemy/issues/1559

### CODE REVIEW

**Comment by dkent600** [comment]
Please allow us to merge this after the dev branch is ready.  It is currently informally locked.

**Comment by dOrgJelli** [comment]
This PR also updates DAOcreator to v8 fixes kovan supports.

**Comment by orenyodfat** [comment]
@dOrgJelli  https://github.com/dOrgTech/DAOcreator/issues/493

**Comment by dOrgJelli** [comment]
Replied @orenyodfat

**Pull request merged**
