### PR TITLE
1153 mixpanel

### PR DESCRIPTION
**Pull request by tibetsprague**
https://daostack.tpondemand.com/RestUI/Board.aspx#page=board/5209716961861964288&appConfig=eyJhY2lkIjoiQjgzMTMzNDczNzlCMUI5QUE0RUE1NUVEOUQyQzdFNkIifQ==&boardPopup=feature/1153/silent

Added an enum of all the “pages” in the app - meaning the screens we think of separate pages for the user.
I also refactored the redemptions code a bit.

### CODE REVIEW

**Comment by leviadam** [comment]
This is waiting for some legal thing.
Plz do not merge.

**Comment by A-Zak** [comment]
Hey @tibetsprague (and @jellegerbrandy)
I went over the mixpanel preview app and played a bit with the reports in mixpanel and it looks pretty darn good... 💪 :)

I was able to answer all sorts of interesting questions so I think we're good to go! :)

I did find a little bug in the staking, but I'll open another issue for that :)

**Comment by A-Zak** [comment]
BTW @tibetsprague what is the "Transition Proposal" event? :)

**Comment by tibetsprague** [comment]
hah @A-Zak you wrote it :) https://docs.google.com/spreadsheets/d/1cjAzaJK1-lAmZBg_DVhTU3HNvL07IGPfSrETi3ERX5s/edit#gid=1535753836

**Pull request merged**
