### PR TITLE
integrate WalletConnect

### PR DESCRIPTION
**Pull request by dkent600**
- integrate with WalletConnect
- upgrade Web3Connect
- abandon the @daostack fork of Web3Connect
- When the user can connect (so the Connect button is showing), I changed the account profile dropdown from saying "Log In" to "Connect", and made it use the cached provider like the Connect button does.  (I think also that we should check for a cached provider everywhere where we automatically ask the user to log in.)  (see https://daostack.tpondemand.com/RestUI/Board.aspx#page=board/5209716961861964288&appConfig=eyJhY2lkIjoiQjgzMTMzNDczNzlCMUI5QUE0RUE1NUVEOUQyQzdFNkIifQ==&boardPopup=bug/1648/silent)
- improved the layout of the login/logout buttons in the account profile dropdown

Resolves:  https://daostack.tpondemand.com/RestUI/Board.aspx#page=board/5209716961861964288&appConfig=eyJhY2lkIjoiQjgzMTMzNDczNzlCMUI5QUE0RUE1NUVEOUQyQzdFNkIifQ==&boardPopup=feature/1552/silent
Partially resolves:  https://daostack.tpondemand.com/RestUI/Board.aspx#page=board/5209716961861964288&appConfig=eyJhY2lkIjoiQjgzMTMzNDczNzlCMUI5QUE0RUE1NUVEOUQyQzdFNkIifQ==&boardPopup=bug/1648/silent

### CODE REVIEW

**Comment by dkent600** [comment]
Currently on hold because our unit tests are failing because of an npm package management issue with web3connect.

**Comment by jellegerbrandy** [comment]
There's also a lint error  on travis (which is likely unrelated)

 The unit-test error comes from the squarelink node module. This does not seem to be something we need (right?). Can we exclude the dependency?

**Comment by jellegerbrandy** [comment]
I fixed the lint  error

**Comment by jellegerbrandy** [comment]
When trying this out with portis, this happens:
- click connect
- click on the portis link
- a portis popup opens with a  "continue" button, I click on it
- a portis walet popup opens asking me to log in
- I log in with user and password, see no error, window closes and I am back to the "continue" step

In the log, I see lots of errors: 
image

-

**Comment by dkent600** [comment]
@jellegerbrandy 

> the unit-test error comes from the squarelink node module. Th

This is precisely why I'm waiting for the release of this PR from web3:  https://github.com/web3connect/web3connect/pull/79

BTW note that the present PR (the one you are reviewing) is still a "WIP".

**Comment by dkent600** [comment]
@jellegerbrandy 

> When trying this out with portis, this happens

Works fine for me.  This is reminiscent of your problems with Portis and Fortmatic; I don't recall how you solved those.  Can you please try it at web3connect.com?

**Comment by jellegerbrandy** [comment]
Testing locally on localhost:3000 with `npm run start-prod`

WalletConnect:
----------------------
- connecting via QR code using Trust wallet works fine
- trying to sign a transaction (preapprove GEN): I get not feedback in alchemy, but an error message in the trust wallet "Parameter specified as non-null is null..."
- trying to save my profile (sign message): error message "cannot read property await of undefined"

Portis
------------
- does nto work with chrome (but that seems just for me?), so testing in firefox
- login works, but after login, the portis popup "to coninue on Alchemy, log in to portis...." is nt closed
- pre-approve: tested up to "confirm" action, which looked good, did not test actual tx as I did not have any funds (any way to test this with rinkeby?)
- saving profile info: "FAILURE: r_ready is undefined"

Fortmatic
----------------
- pre-approve: tested up to "confirm" action, looks good,did not test the actual tx as I did not have any funds (is is possible to test on rinkeby?)
- saving profile info: "FAILURE: this.enqueue is not a function"

------------------


-

**Comment by dkent600** [comment]
@jelle  Both Portis and Fortmatic work in rinkeby

**Comment by dkent600** [comment]
@jellegerbrandy I was able to stake using TrustWallet no problem, on mainnet.

If you want to test WalletConnect on rinkeby, and you have an Android phone, I recommend installing the Rinkeby version of Safe on your phone and try that.  That app doesn't work for me on iOS, but Alex has had luck with it on Android.

**Comment by dkent600** [comment]
@jellegerbrandy I just tried staking using TrustWallet on mainnet and was able to sign the tx on the mobile, but then nothing happened in the app.  Something is wrong.

**Comment by dkent600** [comment]
@jellegerbrandy 

> this is blocking, because as is, I cannot connect with my usual wallet (i.e. with metamask) (unless i delete the localstorage thing)

You have to login, then logout again.

**Pull request merged**
