### PR TITLE
Fix UI where votes screwed up

### PR DESCRIPTION
**Pull request by roienatan**
resolves: https://github.com/daostack/alchemy/issues/2047

### CODE REVIEW

**Comment by dkent600** [comment]
the up/down % numbers need to align left-justified

**Comment by dkent600** [comment]
BTW, note I am pretty sure this is fixed in Alchemy 1.0

**Comment by roienatan** [comment]
> the up/down % numbers need to align left-justified

Not sure what you mean, please explain.

**Comment by roienatan** [comment]
> BTW, note I am pretty sure this is fixed in Alchemy 1.0

I've seen the PR you tagged in the issue but I don't see the changes there are related to this UI issue.

**Comment by roienatan** [comment]
> test failing

Updated arc.js, test env and subgraph.

**Pull request merged**
