### PR TITLE
Upgrade to webpack 4

### PR DESCRIPTION
**Pull request by tibetsprague**
Upgrade webpack-dev-server to version that isnt vulnerable

FIxes https://github.com/daostack/alchemy/issues/233

### CODE REVIEW

**Comment by leviadam** [comment]
@jellegerbrandy 
It looks like @tibetsprague put it also in the `package.json`.
Maybe I misunderstood your comment.

**Comment by jellegerbrandy** [comment]
mm, yes, I see it as well now, I don't know what I was thinking

**Comment by jellegerbrandy** [comment]
@tibetsprague what about this PR? Can you merge from master and see if the test passes?

**Comment by jellegerbrandy** [comment]
@tibetsprague I've merged latest master in here, but the webpack compilation is failing. Can you have another look?

**Comment by tibetsprague** [comment]
This is working for me locally, so im down to merge in despite failing build related to IPFS, ill let you decide. I did merge in the latest from dev

**Comment by jellegerbrandy** [comment]
It is a new, changed, ipfs image, that set the user in the docker container o "ipfs", that messed up the build.

**Comment by jellegerbrandy** [comment]
I fixed the ipfs error, but there is staill a webpack-related error... :-/

**Pull request merged**
