### PR TITLE
fix #10: remove `immutability-helper`

### LINKED ISSUE #10: `Cannot invoke an expression whose type lacks a call signature.` error after fresh clone.
The project fails to compile after a fresh clone and `yarn start` with this error:
```
ERROR in [at-loader] ./src/reducers/arcReducer.ts:91:13
    TS2349: Cannot invoke an expression whose type lacks a call signature. Type 'typeof "/home/matan/Projects/daostack/alchemy/node_modules/immutability-helper/index"' has no compatible call signatures.

ERROR in [at-loader] ./src/reducers/arcReducer.ts:101:14
    TS2349: Cannot invoke an expression whose type lacks a call signature. Type 'typeof "/home/matan/Projects/daostack/alchemy/node_modules/immutability-helper/index"' has no compatible call signatures.

ERROR in [at-loader] ./src/reducers/arcReducer.ts:106:15
    TS2349: Cannot invoke an expression whose type lacks a call signature. Type 'typeof "/home/matan/Projects/daostack/alchemy/node_modules/immutability-helper/index"' has no compatible call signatures.

ERROR in [at-loader] ./src/reducers/arcReducer.ts:113:14
    TS2349: Cannot invoke an expression whose type lacks a call signature. Type 'typeof "/home/matan/Projects/daostack/alchemy/node_modules/immutability-helper/index"' has no compatible call signatures.

ERROR in [at-loader] ./src/reducers/arcReducer.ts:121:14
    TS2349: Cannot invoke an expression whose type lacks a call signature. Type 'typeof "/home/matan/Projects/daostack/alchemy/node_modules/immutability-helper/index"' has no compatible call signatures.
webpack: Failed to compile.
```

Also, I would suggest using es6 synthax for updating an immutable structure instead of having a dependency:
```
const x = {a: 1, b: 2};
const y = {...x, b: 3} // {a: 1, b: 3}
// an array would also work.
```

### PR DESCRIPTION
**Pull request by dev-matan-tsuberi**
since it has been causing problems for me and @leviadam.

### CODE REVIEW

**Comment by tibetsprague** [comment]
um, please dont merge stuff without getting approval. I am going to roll this back because I really don't want to get stuck without immutability helpers

**Comment by leviadam** [comment]
I agree with tibet. I think we will turn master to a protected branch. Agree?

**Comment by dev-matan-tsuberi** [comment]
Sure, @tibetsprague the PR is not yet reverted, do you still want to roll it back?

**Comment by tibetsprague** [comment]
I turned master into a protected branch and for now started working without immutability helper. so, at this moment I dont really want to roll back. though I do want to use immutability helper in the future as it is less verbose and more powerful

**Comment by tibetsprague** [comment]
so yes at some point I want to switch back, but honestly not at this exact moment :)

**Pull request merged**
