### PR TITLE
New proposal button is now disabled when a plugin is not activated yet

### PR DESCRIPTION
**Pull request by roienatan**
resolves: https://github.com/daostack/alchemy/issues/2044

When training tooltip is enables it looks like this now:
Screen Shot 2020-08-06 at 13 57 06

### CODE REVIEW

**Comment by orenyodfat** [comment]
> I would do a regular tooltip, so it is always available to the user (or best, a message right on the page). This isn't really a question of training. It is a context-sensitive state that needs to be more proactively explained to the user when it happens.

the tooltip is annoying . we might remove that at all.

**Comment by roienatan** [comment]
> > I would do a regular tooltip, so it is always available to the user (or best, a message right on the page). This isn't really a question of training. It is a context-sensitive state that needs to be more proactively explained to the user when it happens.
> 
> the tooltip is annoying . we might remove that at all.

@orenyodfat  @dkent600 What do you guys think about a regular tooltip (like the one you have when you hover above Alchemy logo)? Or just adding the text from the left of the button.

**Comment by roienatan** [comment]
Please let me know what you guys think:
Screen Shot 2020-08-06 at 16 16 53

**Comment by dkent600** [comment]
> > I would do a regular tooltip, so it is always available to the user (or best, a message right on the page). This isn't really a question of training. It is a context-sensitive state that needs to be more proactively explained to the user when it happens.
> 
> the tooltip is annoying . we might remove that at all.

I would only be there when the button is disabled.

**Pull request merged**
