### PR TITLE
Make sure proposer name doesn't overlap avatar on proposal history rows

### PR DESCRIPTION
**Pull request by tibetsprague**
Fixes: https://github.com/daostack/alchemy/issues/1551

This took much longer to figure out than it looks :)

### CODE REVIEW

**Comment by orenyodfat** [comment]
why https://alchemy-1551-history-ro-rffoae.herokuapp.com/ does not SHOW_ALL_DAOS as other review app are ?  @tibetsprague

**Comment by tibetsprague** [comment]
@orenyodfat i dont know, but why does that effect this review?

**Comment by orenyodfat** [comment]
> @orenyodfat i dont know, but why does that effect this review?

because review app does not work as expected .even though it rebased on dev

**Comment by tibetsprague** [comment]
@orenyodfat slug size is too big, thats why

**Pull request merged**
