### PR TITLE
lowercase tokens, proposalState to RedemptionsTip

### PR DESCRIPTION
**Pull request by dkent600**
bugs found while investigating the PrimeDAO redeeming bug

### CODE REVIEW

**Comment by roienatan** [comment]
So it fixed the issue? I wonder why it's not happened while redeeming other items...

**Comment by dkent600** [comment]
> I wonder why it didn't happen while redeeming other items...

No this doesn't fix the Redeem problem.  That appears to be happening in the contracts somewhere.  In the course of investigating we found these two other issues in Alchemy.  One causes the token name not to be displayed.  The other causes the tooltip to not appear over the Redeem button.

**Comment by roienatan** [comment]
> > I wonder why it didn't happen while redeeming other items...
> 
> 
> 
> No this doesn't fix the Redeem problem.  That appears to be happening in the contracts somewhere.  In the course of investigating we found these two other issues in Alchemy.  One causes the token name not to be displayed.  The other causes the tooltip to not appear over the Redeem button.

I think it appears on other items.
What issue the change in ActionButton solves?

**Comment by dkent600** [comment]
> What issue the change in ActionButton solves?

The tooltip not to appear over the Redeem button.

**Review by roienatan — APPROVED** [review]

**Pull request merged**
