### PR TITLE
Release 0.10.8

### PR DESCRIPTION
**Pull request by dkent600**

### CODE REVIEW

**Comment by orenyodfat** [comment]
I am still seeing the discuss issue https://alchemy-release-mainnet.herokuapp.com/dao/0x519b70055af55a007110b4ff99b0ea33071c720a  :
Screen Shot 2020-05-21 at 8 10 50

**Comment by orenyodfat** [comment]
re gs send eth  : when value is 0 it should also be mentioned in the card.
see the upper one.
https://alchemy-release-mainnet.herokuapp.com/dao/0x519b70055af55a007110b4ff99b0ea33071c720a/scheme/0xe61d663c6c64ef3177da998f2739c1c59f5bed63e3afdeeb12182a8920e4da76

**Comment by dkent600** [comment]
> when value is 0 it should also be mentioned in the card.
see the upper one.

What is the point of doing that?  In any case, you should create a ticket if you want this.

**Comment by dkent600** [comment]
@orenyodfat 

> I am still seeing the discuss issue

 I need a repro case.  Works fine for me. The link you gave tells me nothing.

**Comment by orenyodfat** [comment]
> > when value is 0 it should also be mentioned in the card.
> > see the upper one.
> 
> @orenyodfat @EzraWeller
> 
> What is the point of doing that? In any case, you should create a ticket if you want this in a future release. Otherwise it is assumed this is required in this release.

so the user will know what the proposal is about . 
please create a ticket for that and add that for next release

**Pull request merged**
