### PR TITLE
feat: hide add proposal button if empty schemes array

### PR DESCRIPTION
**Pull request by Razzwan**

### CODE REVIEW

**Review by roienatan — CHANGES_REQUESTED** [review]
Here for example (https://alchemy-hide-add-propos-fauxpj.herokuapp.com/dao/0x6a041608fa575168957e53c6b6db9a76771fe011), the plugin is not supported and the New Proposal button is stuck.
I think we should not consider an unsupported scheme in the our count. Please suggest @orenyodfat

**Comment by Razzwan** [comment]
> Here for example (https://alchemy-hide-add-propos-fauxpj.herokuapp.com/dao/0x6a041608fa575168957e53c6b6db9a76771fe011), the plugin is not supported and the New Proposal button is stuck.
> I think we should not consider an unsupported scheme in the our count. Please suggest @orenyodfat

Agreed, will doing

**Comment by roienatan** [comment]
@Razzwan It's showing `0` instead of empty space, please fix.
image

**Comment by Razzwan** [comment]
> @Razzwan It's showing `0` instead of empty space, please fix.
> image

Fixed

**Review by roienatan — APPROVED** [review]

**Pull request merged**
