### PR TITLE
Adding DxDAO Token Registry GenericScheme

### PR DESCRIPTION
**Pull request by nicoelzer**
Adding a GenericScheme that allows the DxDAO to curate Token Registries through DAOstack Proposals.

### CODE REVIEW

**Comment by nicoelzer** [comment]
@tibetsprague could we get this merged to live and alchemy-staging-rinkeby.herokuapp.com?

**Comment by tibetsprague** [comment]
That process is more up to @orenyodfat. May not happen until early next week

**Comment by dkent600** [comment]
Review app is here:  https://alchemy-dxdao-tcr-ithrtrvrytx9.herokuapp.com/

**Comment by orenyodfat** [comment]
@nicoelzer is that been tested and approved by you using the review app in rinekby ?
could you please add the test procedure somewhere in the pr description ?

**Pull request merged**
