### PR TITLE
release 0.10.3

### PR DESCRIPTION
**Pull request by dkent600**

### CODE REVIEW

**Comment by EzraWeller** [comment]
Issues that should be resolved before release:
Resolves: #1539
Issues that don't need to be resolved before release:

Other small things:

**Comment by dOrgJelli** [comment]
Fix for #1539 here @EzraWeller @dkent600: https://github.com/daostack/alchemy/pull/1541

**Comment by dkent600** [comment]
@EzraWeller The must-fix is purportedly fixed:  https://github.com/daostack/alchemy/pull/1541

**Comment by dkent600** [comment]
@EzraWeller I create this for the Metamask display issue:  https://github.com/daostack/alchemy/issues/1542

**Comment by dkent600** [comment]
@EzraWeller Is this required to release:  https://github.com/daostack/alchemy/issues/1540?

**Comment by dkent600** [comment]
Blocked by:  https://github.com/daostack/alchemy/issues/1540#issuecomment-604573718

**Comment by EzraWeller** [comment]
On second thought, I would say release not blocked by #1540, but it's something we should have on the todo list.

**Comment by EzraWeller** [comment]
Okay, updated my above comment with a few more small things, but overall: approved. #1540 does seem like an issue we should address in a future release, though I'm not sure how.

**Pull request merged**
