### PR TITLE
at least execute if can't redeem

### PR DESCRIPTION
**Pull request by dkent600**
Resolves: https://github.com/daostack/alchemy/issues/1967https://github.com/daostack/alchemy/issues/1967

### CODE REVIEW

**Comment by orenyodfat** [comment]
how the redeem related to execute button ? is this is same at 1.0 ?

**Comment by dkent600** [comment]
> how the redeem related to execute button ? is this is same at 1.0 ?

This logic is not in 1.0.

First I'll refer you to this comment in the ticket: https://github.com/daostack/alchemy/issues/1967

Second, this comment from Jorden who wrote the code:

`// Call redeemRewards to both execute the proposal and redeem the ContributionReward rewards`

**Comment by orenyodfat** [comment]
No execute button at all ?
https://alchemy-fixexecutepropo-igale7.herokuapp.com/dao/0x790e3ed4b75b357f882cb595b2d233da799a1207/plugin/0x3b17658b687be9d70069119402037caf584448aa37d72a2f098d7914ffd41f85

Screen Shot 2020-07-18 at 10 20 05

**Comment by dkent600** [comment]
> No execute button at all ?

That proposal is expired.

**Comment by orenyodfat** [comment]
Yes. So it need to be able to be excuted
Normally it is done by the bot

**Comment by dkent600** [comment]
> Yes. So it need to be able to be excuted
> Normally it is done by the bot

For what it is worth, Alchemy has always assumed that the bot will be running.  Adding an execute button in this case (and it is not clear to me how we define this case) involves some thought and is not within the scope of this PR.

**Pull request merged**
