### PR TITLE
Styled enable predictions button and enable predictions pretransactio…

### PR DESCRIPTION
**Pull request by brodeur**
…n modal

### CODE REVIEW

**Comment by brodeur** [comment]
https://daostack.tpondemand.com/RestUI/Board.aspx#page=board/5209716961861964288&appConfig=eyJhY2lkIjoiQjgzMTMzNDczNzlCMUI5QUE0RUE1NUVEOUQyQzdFNkIifQ==&boardPopup=bug/1072/silent

**Comment by tibetsprague** [comment]
thought I had already fixed the margins of the modal on dev

**Comment by A-Zak** [comment]
looks much better :)

**Comment by A-Zak** [comment]
looks much better :)

**Pull request merged**
