### PR TITLE
use contract alias for plugin name

### PR DESCRIPTION
**Pull request by dkent600**
Resolves: https://github.com/daostack/alchemy/issues/1766
Resolves: https://github.com/daostack/alchemy/issues/1789

Resolving the 1789 was necessary because splitting camel casing wasn't working right.

But need to confirm that splitting camel-casing is what we want.  We've always been doing it.  It will now be more apparent.

### CODE REVIEW

**Comment by orenyodfat** [comment]
travis is red @dkent600

**Comment by orenyodfat** [comment]
whats the logic behind parsing the scheme alias?  : 
for example , how [GenericSchemeDXTokenRegistry](https://github.com/daostack/subgraph/blob/master/daos/mainnet/dxdao.json#L34)  show up as `Generic Scheme DXToken Registry`

**Comment by dkent600** [comment]
> whats the logic behind parsing the scheme alias? :

Mostly the same as it always has been.  But herein I created a function for it, and documented it.

See the changes here:  
https://github.com/daostack/alchemy/pull/1790/files#diff-57d57172ecb5dd8b766a8fa1431a4dd4

**Comment by orenyodfat** [comment]
> > whats the logic behind parsing the scheme alias? :
> 
> The same as it always has been. But herein I created a function for it, and documented it.
> 
> See the changes here:
> https://github.com/daostack/alchemy/pull/1790/files#diff-57d57172ecb5dd8b766a8fa1431a4dd4

not sure that this logic is good. 
Users/daos  should have the freedom to give what ever title they wish. in that case they should pr that to subgraph, currently ,  later on there will be other way to do that.

**Comment by dkent600** [comment]
> not sure that this logic is good.

OK, just note in the code for `schemeName` that we already hardcode the renaming of several Arc contracts.  Let me know how you'd like it to work.

**Comment by orenyodfat** [comment]
> > not sure that this logic is good.
> 
> OK, just note in the code for `schemeName` that we already hardcode the renaming of several Arc contracts, when there is no meaningful alias. Let me know how you'd like it to work.

when ever `alias` is exist for a scheme set the name of the plugin as the alias .
otherwise use what is done so far.

**Pull request merged**
