### PR TITLE
Support Torus (issue #1829)

### PR DESCRIPTION
**Pull request by roienatan**

### CODE REVIEW

**Comment by roienatan** [comment]
There is a problem with the z-index of the Torus popup. I'm fixing it...

**Comment by orenyodfat** [comment]
see https://github.com/daostack/alchemy/commit/870ec7dbd406cdfd830b348c156e97a04ba47929

**Comment by orenyodfat** [comment]
> There is a problem with the z-index of the Torus popup. I'm fixing it...

see https://github.com/daostack/alchemy/commit/870ec7dbd406cdfd830b348c156e97a04ba47929

**Comment by roienatan** [comment]
Right, I saw it on master branch. It's interesting that locally I had no problem with the z-index.

**Pull request merged**
