### PR TITLE
New DAOcreator UI Embedded

### PR DESCRIPTION
**Pull request by dOrgJelli**
paste

### CODE REVIEW

**Comment by orenyodfat** [comment]
@cbrzn travis fail :(

**Comment by orenyodfat** [comment]
@dOrgJelli is that only a UI update ?

**Comment by orenyodfat** [comment]
@tibetsprague @dkent600 any idea why test fail ?

**Comment by EzraWeller** [comment]
Looks good to me. The one small change I suggest before merging is to give at least an estimate of how many transactions to wait for once you've started "installing" the organization.

**Comment by orishim** [comment]
> Looks good to me. The one small change I suggest before merging is to give at least an estimate of how many transactions to wait for once you've started "installing" the organization.

Created an issue for this [here](https://github.com/dOrgTech/DAOcreator/issues/485).  For now we can just add the following warning:

`Installation can require between 2 - 8 transactions. Please confirm all transactions you are prompted to sign.`

What do you think @cbrzn @dOrgJelli ?

**Comment by dkent600** [comment]
@dOrgJelli Update the merge conflicts and I'll merge this.

**Comment by dOrgJelli** [comment]
@dkent600 merged

**Comment by dOrgJelli** [comment]
@EzraWeller @orishim left a comment on the issue Ori created.

**Pull request merged**
