### PR TITLE
Cleaned up buy GEN menu

### PR DESCRIPTION
**Pull request by brodeur**

### CODE REVIEW

**Comment by A-Zak** [comment]
Two comments:
- [ ] 1) it seems we have two lists of "place to by GEN at" (one for the side menu, and one for the staking popup). We should consolidate it to have just one source of truth.
Screenshot 2019-05-16 at 15 03 03
Screenshot 2019-05-16 at 15 02 49


- [ ] 2) let's align the icons and labels a bit better... 
alignment guide

**Comment by A-Zak** [comment]
Also, please put BitFinex above EthFinex... :)
They are after all the parent company :)

**Comment by leviadam** [comment]
@brodeur I think ethfinex is still not aligned in the menu.

**Comment by leviadam** [comment]
Also, the two menus are different, there is no one source of truth as @A-Zak called it.

**Comment by brodeur** [comment]
Alright, I think I got it to where we want it after talking with Alex today. Let me know if further changes are needed

**Comment by leviadam** [comment]
Actually @brodeur the icons are not centered.
In addition, the menu is not read from one source of truth.

**Comment by leviadam** [comment]
OK. We can probably delay the single source of truth. Better merge this.

**Comment by A-Zak** [comment]
@jellegerbrandy Does it matter what we do with this conflict in the package-lock important? or will it work either way? :)

**Comment by A-Zak** [comment]
If not, can you please merge? :) 🙏

**Pull request merged**
