### PR TITLE
Activate Please log in button in header

### PR DESCRIPTION
**Pull request by tibetsprague**
Still needs styling from @brodeur

### CODE REVIEW

**Comment by jellegerbrandy** [comment]
This is actually more complex, and I do not thing "enable metamask" is the correct semantics for that button. We've got an ongoing discussion here: https://github.com/daostack/alchemy/issues/325 (see the last comments)

**Comment by tibetsprague** [comment]
Well yes, thats true, but aren't we waiting on more design details from Alex? In the meantime this allows us to use Alchemy with MetaMask and privacy mode turned on

**Comment by tibetsprague** [comment]
@A-Zak could use more of your input here too. we do need a button like this to allow people to work with MetaMask's privacy mode on, which is now the default

**Comment by jellegerbrandy** [comment]
I borrowed some of yor logic for PR #485 , closing this one...

**Pull request closed without merging**
