### PR TITLE
remove large error messages

### PR DESCRIPTION
**Pull request by dev-matan-tsuberi**

### CODE REVIEW

**Comment by tibetsprague** [comment]
I wonder if we should console.log the full error, mostly for development purposes?

**Comment by dev-matan-tsuberi** [comment]
But I don't want them to appear in the final build. Do we have a webpack variable that's injected into the app that indicates if its a `prod` or `dev` build?

**Comment by dkent600** [comment]
As long as we're in alpha/beta testing mode it might be helpful to keep those console messages.

**Comment by dev-matan-tsuberi** [comment]
Done in: https://github.com/daostack/alchemy/pull/60/commits/e6c9b3adbf7d24357fae85e679b4085cc22ab777

**Pull request merged**
