### PR TITLE
Daocreator xdai support

### PR DESCRIPTION
**Pull request by cbrzn**
Resolves: https://github.com/daostack/alchemy/issues/1741

### CODE REVIEW

**Comment by cbrzn** [comment]
- Contracts used for creation are now from version 0.0.1-rc.41
- UGenericScheme is no longer supported
- Migration script updated to support xdai

@dkent600

**Comment by dkent600** [comment]
@orenyodfat Can you please review that we're OK with taking the changes that @cbrzn listed in this comment:  https://github.com/daostack/alchemy/pull/1791#issuecomment-637681591?

**Comment by orenyodfat** [comment]
Heroku build fail @cbrzn

**Comment by cbrzn** [comment]
@orenyodfat not sure how can I fix that... maybe sharing the heroku logs might help to know what the problem is?

**Comment by orenyodfat** [comment]
it looks like an out of memory issue 
`"FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory" `
does the new DAOCreator might  include any dramatic change re memory usage ?

**Comment by dkent600** [comment]
Change `devtool: 'source-map' to `devtool: 'cheap-source-map' in webpack.prod.config.js.  This will fix the problem.  This change will soon likely be in dev in any case.

**Comment by cbrzn** [comment]
> does the new DAOCreator might include any dramatic change re memory usage ?

Negative sir

> Change devtool: 'source-map' to devtool: 'cheap-source-map' in webpack.prod.config.js. This will fix the problem. This change will soon likely be in dev in any case.

So this is a problem with alchemy and not dao creator, right? Doing it now, thanks Doug!

**Comment by dkent600** [comment]
Weird, the travis build succeeded, but here was it did not complete

**Pull request merged**
