### PR TITLE
Support CL4R

### PR DESCRIPTION
**Pull request by roienatan**
resolves: #2386
resolves:  #1811
resolves:  #2385

### CODE REVIEW

**Comment by orenyodfat** [comment]
please use https://github.com/daostack/arc.js/releases/tag/0.2.83

**Comment by orenyodfat** [comment]
information tab : 
- [ ] token : add name of token near the address
- [ ] batch time : should be in days units 
- [ ] constA should be displayed in  a readable number  format e.g ( 85000 REP) 
- [ ] constB should be displayed in readable decimal format e.g (0.9) .

Screen Shot 2021-01-21 at 20 54 56

**Comment by orenyodfat** [comment]
- [ ] Something the locks can be shown even the user is not login .
- [ ] `Please Login` should be something like 'Please Login to your wallet to see your locks' 

Screen Shot 2021-01-21 at 21 00 54

**Comment by orenyodfat** [comment]
convert const A + B from realNumbers 
so in this case
-  const A should be 85000 rep 
- const B should be 0.9 
Screen Shot 2021-01-23 at 0 24 39

**Comment by orenyodfat** [comment]
wrong (active) date 

Screen Shot 2021-01-23 at 0 27 06

**Comment by roienatan** [comment]
> wrong active/inactive date 
> 
> in this case it should be `active` 
> 
> 
> 
> Screen Shot 2021-01-23 at 0 27 06
> 
> 

The lock has ended so it's inactive. Maybe it's not the best place to put it.

**Review by orenyodfat — APPROVED** [review]

**Pull request merged**
