### PR TITLE
Feed fixes

### PR DESCRIPTION
**Pull request by tibetsprague**
follow buttons on feed items and dao sidebar

modal asking about connecting to 3box

### CODE REVIEW

**Comment by tibetsprague** [comment]
@jellegerbrandy i cant reproduce something on top of the home button, or gray and blue. where/how are those?

**Comment by tibetsprague** [comment]
ok found the issue on mobile with the follow button on top of home button. 

even bigger issue though, how are you signing the messages with the 3box modal still open! metamask shouldnt do anything until you select the Got It button, and then the modal closes. that is super weird. can you show me how to reproduce?

**Comment by tibetsprague** [comment]
@jellegerbrandy and @A-Zak not sure how to solve the last "problem" where it doesn't ask you to sign messages. basically what is happening is 3box caches your login info so you don't have to sign messages again once you already have on a machine, unless we log the person out, which we are supposed to do when they press Log out (haven't implemented that yet, its unfortunately hard because of some issues of the way the log in stuff is architected right now). @A-Zak what do you think about only showing the 3box modal once? or rather once they have gone ahead and done a 3box action once we no longer show it? then we can also get rid of the Do not show again checkbox.

**Comment by A-Zak** [comment]
@tibetsprague 

The ״ambegious" follow buttons on the feed items should follow the item the card is presenting (the way it's implemented now)... if it's a proposal, then the proposal. if it's a person then the person, etc....

The reason is simple, we want people to follow things, rather than unfollow them (like in what @jellegerbrandy suggested ^_^)

- - - - -

Re showing the popup once, I'm not sure I understand the problem / solution... let's talk about it now in the call ^_^

**Comment by tibetsprague** [comment]
@A-Zak the buttons do follow the right content, @jellegerbrandy issue is the name of the button is not clear. should we change it to Follow Proposal? like i said it does tell you what you are following when you mouseover, so maybe thats ok

**Comment by tibetsprague** [comment]
the other issue we can discuss tomorrow

**Comment by tibetsprague** [comment]
@jellegerbrandy the ones i cant reproduce are the gray text on blue background and...

"how are you signing the messages with the 3box modal still open! metamask shouldnt do anything until you select the Got It button, and then the modal closes. that is super weird. can you show me how to reproduce?"

**Comment by tibetsprague** [comment]
@A-Zak log out has been implemented

**Comment by A-Zak** [comment]
Hey @tibetsprague here's some feedback 😅

* When the page first loads, it shows the "you'r not following anything" image and only after a few seconds it switches to the feed...
* "Excuse me, who are you?" > "Hi there! Have we met before?"
    * "Please Log In to see your personal feed" > ""
* Weird spacing in proposal details
    * Screenshot 2019-12-17 at 23 10 05
    * Actually most of the vertical spacings are a little off...
* Can we make the pagination "smaller"? say, only 10 events at a time?
    * Can we load it by date? I.e. load two days of events...
* Shadow is a little too strong
    * The shadow of the top part of the card should not be above the bottom part
* (i) & (+) are a different color (screenshot)
    * Screenshot 2019-12-17 at 23 22 34
    * Is this a problem with the assets or something else
* Voted with XXXXXXXXX rep is a little too detailed, let's round to two digits after the dot.
    * Screenshot 2019-12-17 at 23 25 47
* No follow button for the DAO on sidebar
* When unfollowing something, when we're waiting with the spinner, the button should read "unfollow" (now shows "following")
* Seems like we have some duplicate events going on
    * entering quiet ending seems to always also generate a vote flip event
    * Screenshot 2019-12-17 at 23 33 41
* We don't need to show "expired in queue" events for all the proposals of a DAO we follow, only if we follow the specific proposal
* For proposals with a long description, we need to show a show full details button :)
    * Screenshot 2019-12-17 at 23 37 47
* Status names
    * "Proposal is executed"
        * Can we say "proposal has passed" / "... failed" instead?
    * "proposal is QuietEndingPeriod"
        * Proposal is in overtime
        * (Please also change the status in the proposal page from "quiet ending" to "Boosted (overtime)"
            * e.g. https://alchemy.daostack.io/dao/0x519b70055af55a007110b4ff99b0ea33071c720a/proposal/0xe5f655b75c317f59105013b9c07b978c0b97d28fc5787794ad178667375cd693
    * "proposal is PreBoosted"
        * Proposal is now pending
    * "Proposal is boosted"
        * Can we do the "boosted" in bold?

**Comment by tibetsprague** [comment]
> Weird spacing in proposal details

are you sure? look at the proposal page, should have the same spacing

**Comment by tibetsprague** [comment]
> * Can we load it by date? I.e. load two days of events...

i almost asked you about loading by date. only problem is some dates may have lots of events and some may have none, so that makes it harder to work with dates with predictability. i do think loading by date would like nice, with a header for each day

**Comment by tibetsprague** [comment]
> (i) & (+) are a different color (screenshot)

what the heck? that is not the info image i see, no idea why you are seeing that

**Comment by tibetsprague** [comment]
> * No follow button for the DAO on sidebar

already fixed in this PR

**Comment by tibetsprague** [comment]
> * When unfollowing something, when we're waiting with the spinner, the button should read "unfollow" (now shows "following")

would be much easier to just make the button say Unfollow when you are already following something. which was a request by doug and Jelle too. can we just do that @A-Zak ?

**Comment by tibetsprague** [comment]
> * The shadow of the top part of the card should not be above the bottom part
Fixed

**Comment by tibetsprague** [comment]
> * entering quiet ending seems to always also generate a vote flip event
This is a subgraph issue

**Comment by tibetsprague** [comment]
> Voted with XXXXXXXXX rep is a little too detailed, let's round to two digits after the dot.

fixed

**Comment by tibetsprague** [comment]
> * We don't need to show "expired in queue" events for all the proposals of a DAO we follow, only if we follow the specific proposal

hmm, you told me to show proposal state changes for DAOs, are you saying you only want to ignore expired state changes, but show all the other ones?

**Comment by tibetsprague** [comment]
> For proposals with a long description, we need to show a show full details button :)

its hard to tell if its too long since the formatting can be so different. can we just always show the Show details link? that would be easier and i think it makes sense since its not totally clear you can click on the proposal title

**Comment by tibetsprague** [comment]
> * When the page first loads, it shows the "you'r not following anything" image and only after a few seconds it switches to the feed...

Fixed

**Comment by tibetsprague** [comment]
> Seems like we have some duplicate events going on

anything other than the quiet ending and vote flip events?

**Comment by tibetsprague** [comment]
> * entering quiet ending seems to always also generate a vote flip event

Well yes because you only enter quiet ending period if the vote flips

**Comment by jellegerbrandy** [comment]
@tibetsprague aout the comments above: the only problem that I still can reproduce is this:

* (this on chrome + metamask): I load the app, do my following and unfollowing. I reloaed. I click "follow". I see the modal telling me to sign 2 messages. I click Ok on the modal. I do not see any Metamask messages. Follow and unfollow "just works". 

So in this case, the modal should not have been shown (as it tells me to sign messages, which is not true)

**Comment by tibetsprague** [comment]
@jellegerbrandy fixed

**Comment by A-Zak** [comment]
> > Weird spacing in proposal details
> 
> are you sure? look at the proposal page, should have the same spacing

Yeah, it does look like Luuk wrote some weird makrdown :D
It does look like it does in the proposal details, except for this little glitch
image

**Comment by A-Zak** [comment]
> > * Can we load it by date? I.e. load two days of events...
> 
> i almost asked you about loading by date. only problem is some dates may have lots of events and some may have none, so that makes it harder to work with dates with predictability. i do think loading by date would like nice, with a header for each day

Then how bout we just go for loading 10-20 items at a time? :)

**Comment by A-Zak** [comment]
> > (i) & (+) are a different color (screenshot)
> 
> what the heck? that is not the info image i see, no idea why you are seeing that

looks ok now ¯\_(ツ)_/¯

**Comment by A-Zak** [comment]
> > * When unfollowing something, when we're waiting with the spinner, the button should read "unfollow" (now shows "following")
> 
> would be much easier to just make the button say Unfollow when you are already following something. which was a request by doug and Jelle too. can we just do that @A-Zak ?

So this logic came from twitter/fb... This is my attempt at analysing their decisions / the effects I see this logic creates:
When you're not following the item, you want the button to encourage the user to follow it - hence "follow" is what it says on the button. But when you do follow it you don't want to encourage users to unfollow things so the button turns into sort of a status label. But when you hover over the button, it changes to "unfollow" to make sure you understand what would happen if you click it (similarly the spinners should read @follow & @unfollow to convey what is happening in the bg).


Does this make sense?
@jellegerbrandy @dkent600 @tibetsprague

**Comment by A-Zak** [comment]
> > * entering quiet ending seems to always also generate a vote flip event
> >   This is a subgraph issue

Can we filter it out?
Show all the vote flip events accept the first one that comes with the quiet ending even....

**Comment by A-Zak** [comment]
> > * We don't need to show "expired in queue" events for all the proposals of a DAO we follow, only if we follow the specific proposal
> 
> hmm, you told me to show proposal state changes for DAOs, are you saying you only want to ignore expired state changes, but show all the other ones?

Yup :)
Unless you follow this particular proposal, knowing it expired is not very interesting... :)

**Comment by A-Zak** [comment]
> > For proposals with a long description, we need to show a show full details button :)
> 
> its hard to tell if its too long since the formatting can be so different. can we just always show the Show details link? that would be easier and i think it makes sense since its not totally clear you can click on the proposal title

Hmmm, but even if we show it all the time, we still have to somehow tell the user if this is the full description of the proposal or if there's more to it.....

Can't we just "render" the full description, and only "crop" it to the max size we want?
(and then just compare the fully rendered description and the max size)

**Comment by A-Zak** [comment]
> > Seems like we have some duplicate events going on
> 
> anything other than the quiet ending and vote flip events?

no, I don't remember seeing any other ones, I'll let you know if I find any... :)

**Comment by tibetsprague** [comment]
> > > * entering quiet ending seems to always also generate a vote flip event
> > >   This is a subgraph issue
> 
> Can we filter it out?
> Show all the vote flip events accept the first one that comes with the quiet ending even....

@A-Zak  seems important to show to me, people need to know what the vote flipped to, thats highly relevant information

**Comment by tibetsprague** [comment]
> Hmmm, but even if we show it all the time, we still have to somehow tell the user if this is the full description of the proposal or if there's more to it.....
> 
> Can't we just "render" the full description, and only "crop" it to the max size we want?
> (and then just compare the fully rendered description and the max size)

ill explore, but how do you want to tell the user? a link saying Show more details isnt totally clear to me, could add ... to the end of the description but thats not super clear either. One cool way to do it that doesnt require anything fancy is to just have the bottom of the description visually fade out, that way if there is enough description to go below the card you see that it is fading out and now there is more to see. make sense?

**Comment by tibetsprague** [comment]
> Then how bout we just go for loading 10-20 items at a time? :)

yes i changed it to that

**Comment by tibetsprague** [comment]
> When you're not following the item, you want the button to encourage the user to follow it - hence "follow" is what it says on the button. But when you do follow it you don't want to encourage users to unfollow things so the button turns into sort of a status label. But when you hover over the button, it changes to "unfollow" to make sure you understand what would happen if you click it (similarly the spinners should read @follow & @Unfollow to convey what is happening in the bg).

ok, done

**Comment by tibetsprague** [comment]
> Yup :)
> Unless you follow this particular proposal, knowing it expired is not very interesting... :)

seems kinda interesting to me to know when a proposal fails...

**Comment by A-Zak** [comment]
> > > * entering quiet ending seems to always also generate a vote flip event
> > >   This is a subgraph issue
> > 
> > Can we filter it out?
> > Show all the vote flip events accept the first one that comes with the quiet ending even....
> 
> @A-Zak seems important to show to me, people need to know what the vote flipped to, thats highly relevant information

@tibetsprague Can we maybe combine them into one "special" event?
It could have this combined title: "Proposal in overtime - Pass is now in the lead"

**Comment by A-Zak** [comment]
> > Hmmm, but even if we show it all the time, we still have to somehow tell the user if this is the full description of the proposal or if there's more to it.....
> > Can't we just "render" the full description, and only "crop" it to the max size we want?
> > (and then just compare the fully rendered description and the max size)
> 
> ill explore, but how do you want to tell the user? a link saying Show more details isnt totally clear to me, could add ... to the end of the description but thats not super clear either. One cool way to do it that doesnt require anything fancy is to just have the bottom of the description visually fade out, that way if there is enough description to go below the card you see that it is fading out and now there is more to see. make sense?

Fade out sounds good, but it looks a little weird...
looks like it overlaps the "show full details" button...
image

**Comment by A-Zak** [comment]
> > Yup :)
> > Unless you follow this particular proposal, knowing it expired is not very interesting... :)
> 
> seems kinda interesting to me to know when a proposal fails...

I mean i guess it could be interesting in some cases, but I think that in most cases proposals that didn't get boosted are just not interesting enough...
And if we see people follow a lot of regular proposals we can think about adding updates on these events for everyone as well.... :)

**Comment by A-Zak** [comment]
Also two little bugs in the proposal feed cards...
1. there's always a "proposal" prepended to all the proposal titles...
2. the description is ignoring new lines (here every word is in a new line, you can see it in the [proposal details page](https://alchemy-staging-rinkeby.herokuapp.com/dao/0x3cdb39c1ca57c19a316dd2f5acf900705220c713/proposal/0x7706b25a60c74781f14d7a7c855f4627edfcfcbcf3f8fa91b8dd71beafa256ea))...

image

**Pull request merged**
