### PR TITLE
DAO Landing Page

### PR DESCRIPTION
**Pull request by dkent600**
Resolves: https://github.com/daostack/alchemy/issues/1567  (Phase I)

Mock is here: https://www.figma.com/file/qsog4uCensMYaaSclxlmVi/DAO-Front-End-Mocks?node-id=0%3A1

Also:

* cleans up the DAO sidebar menu item text a little

**Note** one bit isn't finished:  Still haven't seen the scrolling behavior with lots of comments in disqus.

### CODE REVIEW

**Comment by EzraWeller** [comment]
I'm not sure about the disqus convos not working -- I don't see any errors on that I've seen.

Everything looks good, except there should still be a "Home" link in each DAO, and what is currently labeled "Proposals" should be "Plugins" (at least for now, because that page's header is "All Plugins"). This is for the "Menu" on the left hand side. Does that make sense?

**Comment by dkent600** [comment]
So the decision is to rename the header on the DaoSchemesPage from "All Plugins" to "Proposal Plugins"

**Comment by EzraWeller** [comment]
The sidebar doesn't seem quite right:
Screen Shot 2020-04-29 at 9 53 25 AM

We still want the "Home" tab to be there, I think (which should go with the house icon), but now it should lead to the new DAO homepage. The "Proposals" tab should have a different icon, maybe a scroll or document if we have that. (So four side bar tabs: Home, Proposals, Members, History)

**Comment by EzraWeller** [comment]
Approved!

**Pull request merged**
