### PR TITLE
Add dOrg Sidebar

### PR DESCRIPTION
**Pull request by orishim**

### CODE REVIEW

**Comment by orenyodfat** [comment]
@orishim whats this pr is bout ? is it still relevant ?

**Comment by orishim** [comment]
Yes, adding custom dOrg sidebar.

**Comment by dkent600** [comment]
> Yes, adding custom dOrg sidebar.

@orishim We really need a complete description of what you want here.  What does this sidebar do?  Why is it important?  Thanks!

**Comment by orishim** [comment]
forget it

**Pull request closed without merging**
