### PR TITLE
Support method arrays params in generic multi-call

### PR DESCRIPTION
**Pull request by roienatan**
resolves: https://github.com/daostack/alchemy/issues/2255

### CODE REVIEW

**Comment by orenyodfat** [comment]
- the numbering should be per call , not per contract.it should be :
# 1
contract(0x...)

not 

Screen Shot 2020-11-11 at 10 05 21

**Comment by orenyodfat** [comment]
I think that adding the param names in the function prototype will give better UI.
so instead of

Screen Shot 2020-11-11 at 10 07 44

it should be

`method approve(address _spender,uint _value,bytes _data)`

**Comment by orenyodfat** [comment]
the ETH value on the new proposal should be displayed only after the user choose a contact along with the list of Abis

**Comment by roienatan** [comment]
> * the numbering should be per call , not per contract.it should be :
>   `# 1`
>   contract(0x...)
> 
> not
> 
> Screen Shot 2020-11-11 at 10 05 21

It's quite the same since each contract is necessarily a call, but okay.

**Comment by roienatan** [comment]
> * the numbering should be per call , not per contract.it should be :
>   `# 1`
>   contract(0x...)
> 
> not
> 
> Screen Shot 2020-11-11 at 10 05 21

Done.

**Comment by roienatan** [comment]
> I think that adding the param names in the function prototype will give better UI.
> so instead of
> 
> Screen Shot 2020-11-11 at 10 07 44
> 
> it should be
> 
> `method approve(address _spender,uint _value,bytes _data)`

Done.

**Comment by roienatan** [comment]
> the ETH value on the new proposal should be displayed only after the user choose a contact along with the list of Abis

As discussed, we will wait with that.

**Review by orenyodfat — APPROVED** [review]

**Pull request merged**
