### PR TITLE
Helper Tour of the app

### PR DESCRIPTION
**Pull request by tibetsprague**
Gets displayed the first time someone views a DAO

### CODE REVIEW

**Comment by dev-matan-tsuberi** [comment]
- "Access the tour later" icon is not aligned with the help icon button:
screenshot from 2018-07-05 00-55-55

- Tour says step 1/8, but there are only 4 steps in total.
- Should the tour start automatically on first visit? didn't start for me.

**Comment by tibetsprague** [comment]
Oh thanks for testing! Yeah we know about the alignment, Aaron is working on it. The steps part is tricky because there are 8 steps if you have a proposal and a boosted proposal in the UI. so we may add fakes ones if they dont exist, but for now we decided this is ok. But yes the tour should appear the first time you view a DAO. Can you see if you have a cookie set called seen_tour?

**Comment by dev-matan-tsuberi** [comment]
@tibetsprague Tried again and it worked. But now I think the disclaimer doesn't show automatically. Cleared my cookies and refreshed and saw `seen_disclaimer` being set to `true` immediately but no disclaimer was shown.

**Comment by tibetsprague** [comment]
yeah the disclaimer cookie is misnamed, that one brings you to the homepage if you try  to view another part of  the app and havent seen the homepage yet. but it is super weird that you  are not seeing the tour automatically appear the first time. still, this is a QA issue, not code review, im going to merge into dev and staging for Dor to test too. ok?

**Pull request merged**
