### PR TITLE
1397 new notifications

### PR DESCRIPTION
**Pull request by brodeur**
https://daostack.tpondemand.com/RestUI/Board.aspx#page=board/5209716961861964288&appConfig=eyJhY2lkIjoiQjgzMTMzNDczNzlCMUI5QUE0RUE1NUVEOUQyQzdFNkIifQ==&boardPopup=userstory/1397/silent

### CODE REVIEW

**Comment by tibetsprague** [comment]
@jellegerbrandy notifications not disappearing is already happening currently, not sure when it broke

**Comment by jellegerbrandy** [comment]
ok then I'll merge this and make a separate issue for the timeout

**Comment by dkent600** [comment]
I don't think this looks so great.  See the top of the close button in the header:

image

**Comment by dkent600** [comment]
And I think errors should probably have a red top border, which is missing:

image

**Comment by dkent600** [comment]
There is no tooltip such as is called-for in the mocl:

image

**Comment by dkent600** [comment]
I really don't get why the colored top-borders are not 100% width in the mock:

image

**Pull request merged**
